### ISSUE TITLE
Why use `echo` in every bash script

### ISSUE THREAD

**Issue by FredrikAugust** [Tijndagamer/bin#5]
Why do you use `echo` before every command in your shell scripts. Why don't you just call them straight there.

And also, why use `#!/bin/sh` over `#!/bin/bash`?

**Comment by Tijndagamer** [comment]
[So](https://github.com/Tijndagamer/bin/blob/4952a75d7ed4c3e1af42aa97ac95517eebcbbb14/backup) [these](https://github.com/Tijndagamer/bin/blob/4952a75d7ed4c3e1af42aa97ac95517eebcbbb14/clearcache) [are](https://github.com/Tijndagamer/bin/blob/4952a75d7ed4c3e1af42aa97ac95517eebcbbb14/monitor_fix) [not]
(https://github.com/Tijndagamer/bin/blob/4952a75d7ed4c3e1af42aa97ac95517eebcbbb14/move_workspace_left) [included](https://github.com/Tijndagamer/bin/blob/4952a75d7ed4c3e1af42aa97ac95517eebcbbb14/move_workspace_right) [in](https://github.com/Tijndagamer/bin/blob/4952a75d7ed4c3e1af42aa97ac95517eebcbbb14/reload_zsh) ["every](https://github.com/Tijndagamer/bin/blob/4952a75d7ed4c3e1af42aa97ac95517eebcbbb14/set_mouse_sen_low) [shell script"?](https://github.com/Tijndagamer/bin/blob/4952a75d7ed4c3e1af42aa97ac95517eebcbbb14/tmux_colors)

Most scripts that use "echo" to call commands are old & shitty.

And for the `#!/bin/sh` vs `#!/bin/bash`, it's a matter of personal preference, and since the speed improvements for using `sh` over `bash` are either non-existent or marginal I won't bother changing it.

**Comment by FredrikAugust** [comment]
Alright, only browsed through a few of them, guess I was really unlucky
then. Either way my eyes burn when I look at it.

It's like having a function whose sole purpose is to call another function

**Comment by Tijndagamer** [comment]
Yup. The scripts are basically aliases which work no matter what shell you're using.
